# Documentation Schema for docs/solutions/ files
# Referenced by /workflows:compound for frontmatter validation.
# This schema describes the frontmatter actually written in practice.

required_fields:
  title:
    type: string
    description: "Short title describing the problem and fix"
    examples:
      - "chore: Restructure /startwork spec to surface all conflicts"
      - "fix: Lounge screen CSS styling"

  date:
    type: string
    pattern: '^\d{4}-\d{2}-\d{2}$'
    description: "Date when this problem was solved (YYYY-MM-DD)"

  category:
    type: string
    description: "Directory name under docs/solutions/. Use kebab-case. Pick from existing categories or create a new one when none fits."
    examples:
      - "ui-bugs"
      - "workflow-spec-gaps"
      - "runtime-errors"
      - "performance-issues"

  problem_type:
    type: enum
    values:
      - build_error          # Compilation, bundle errors
      - test_failure         # Test failures, flaky tests
      - runtime_error        # Exceptions, crashes during execution
      - performance_issue    # Slow queries, memory issues
      - database_issue       # Migration, query, schema problems
      - security_issue       # Authentication, authorization, XSS
      - ui_bug               # Frontend, rendering issues
      - integration_issue    # External service, API integration problems
      - logic_error          # Business logic bugs
      - developer_experience # DX issues: workflow, tooling, dev setup
      - workflow_issue       # Development process, missing steps
      - spec-gap             # Spec that silently omits required data or steps
      - best_practice        # Documenting patterns and practices to follow
      - documentation_gap    # Missing or inadequate documentation
    description: "Primary category of the problem"

  components_affected:
    type: array[string]
    min_items: 1
    description: "File paths or component names affected by this problem"
    examples:
      - ".claude/commands/startwork.md"
      - "src/client/components/Lounge.tsx"

  severity:
    type: enum
    values:
      - critical             # Blocks production or development
      - high                 # Impairs core functionality
      - medium               # Affects specific feature
      - low                  # Minor issue or edge case
    description: "Impact severity"

optional_fields:
  tags:
    type: array[string]
    max_items: 8
    description: "Searchable keywords (lowercase, hyphen-separated)"

  pr:
    type: integer
    description: "PR number that delivered the fix"

  review_deltas:
    type: array[string]
    description: "Changes made during review that differ from the plan"

validation_rules:
  - "date must be in YYYY-MM-DD format"
  - "problem_type must match one of the enum values"
  - "severity must match one of the enum values"
  - "tags should be lowercase, hyphen-separated"
  - "category should be kebab-case, matching a docs/solutions/ subdirectory"
